version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=ecom
        volumes:
            - ./ecom-dump.sql:/docker-entrypoint-initdb.d/dump.sql
        ports:
            - "5432:5432"
    redis:
        image: 'redis:latest'
        ports:
          - "6379"
    nginx:
        image: ${REGISTER_TAG}nginx:latest
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./client
        env_file:
            - ./client/.env
        ports:
            - "3000:3000"
        depends_on:
            - api
            # - client
    api:
        image: ${REGISTER_TAG}api:latest
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        env_file:
            - ./server/.env
        depends_on:
            - postgres
            - redis
        ports:
            - "4000:4000"
        links:
            - redis
    # client:
    #     image: ${REGISTER_TAG}client:latest
    #     stdin_open: true
    #     build:
    #         context: ./client
    #         dockerfile: Dockerfile.dev
    #     volumes:
    #         - /app/node_modules
    #         - ./client:/app