apiVersion: apps/v1
kind: Service
metadata:
    name: api-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: server-api
    ports:
        - port: 4000
            targetPort: 4000
